---
# Manage Galaxy download

- name: Download Galaxy
  block:

    - name: Check for Galaxy download receipt
      stat:
        path: "{{ galaxy_server_dir }}/{{ galaxy_commit_id }}_receipt"
      register: download_receipt

    - name: Create Galaxy server directory
      file:
        path: "{{ galaxy_server_dir }}"
        state: directory

    - name: Install current version of Galaxy
      unarchive:
        src: "{{ galaxy_download_url }}"
        dest: "{{ galaxy_server_dir }}"
        extra_opts: --strip-components=1
        remote_src: yes
      when: not download_receipt.stat.exists

    - name: Create Galaxy download receipt
      file:
        path: "{{ galaxy_server_dir }}/{{ galaxy_commit_id }}_receipt"
        state: touch
      when: not download_receipt.stat.exists

    - name: Include virtualenv setup tasks
      import_tasks: virtualenv.yml

    - name: Remove orphaned .pyc files and compile bytecode
      import_tasks: compile.yml

  remote_user: "{{ galaxy_remote_users.privsep | default(__galaxy_remote_user) }}"
  become: "{{ true if galaxy_become_users.privsep is defined else __galaxy_become }}"
  become_user: "{{ galaxy_become_users.privsep | default(__galaxy_become_user) }}"
